language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip3 install -U pip
  - pip3 install -U pylint
  - pip3 install -r src/client/requirements.txt
  - pip3 install -r src/server/requirements.txt
script:
  - pylint src/client/cassh -d redefined-builtin -d useless-object-inheritance -d too-many-branches
  - pylint src/server/server.py
  - pylint src/server/lib/*.py
  - pylint src/server/ssh_utils/*.py
